### PR TITLE
Update ListView UI in MainWindow.fxml

### PR DESCRIPTION
**Pull request by Kratious**
Progress so far:
image

Planning to change the colour scheme for the rest of the application

### CODE REVIEW

**Comment by Kratious** [comment]
image
Still working on improving the styling for command box, result box and the browser panel

**Comment by Kratious** [comment]
image
Updated user interface

**Comment by iMarbles** [comment]
> image
> Still working on improving the styling for command box, result box and the browser panel

Looks good!

**Comment by iMarbles** [comment]
> image
> Updated user interface

LOOKS GOOD

**Comment by Kratious** [comment]
> 
> 
> Nice work! 2 thoughts:
> 
>     1. The color scheme could be streamlined a little - too many shades of blue seem a little distracting
> 
>     2. The command and command info panel may have to be a little bigger (got to check) as long as the command usage details can fit in completely should be fine 👍

Yep! This isn't a final design, still planning on making changes. Was thinking this could be used for the product demo first.

**Comment by sharan8** [comment]
> > Nice work! 2 thoughts:
> > ```
> > 1. The color scheme could be streamlined a little - too many shades of blue seem a little distracting
> > 
> > 2. The command and command info panel may have to be a little bigger (got to check) as long as the command usage details can fit in completely should be fine 👍
> > ```
> 
> Yep! This isn't a final design, still planning on making changes. Was thinking this could be used for the product demo first.

Sure 👍. We can merge this once the rest have had a look then!

**Pull request merged**
